### ISSUE TITLE
rqt_reconfigure无反应

### ISSUE THREAD

**Issue by TimGor1997** [Xujianhong123Allen/sensor_calibration#4]
您好，请问在rqt_reconfigure窗口中调整xyz，无法过滤点云，显示的点云没有变化是什么问题导致的呢？

**Comment by fanfer** [comment]
您好，我也遇到了相同的问题，请问您之前找到了解决办法了吗？

**Comment by Haishanliu** [comment]
我用的是ouster lidar，也出现了同样的问题。无法过滤点云。请问有解决办法吗？
